version: '3.9'

services:
  app:
    container_name: nestapp-oxygen
    image: nestimg
    build: .
    ports:
      - ${NEST_PORT}:${NEST_PORT}
    environment:
      - DB_TYPE=${DB_TYPE}
      - PG_HOST=${PG_HOST} #doit matcher avec le container_name de la db
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=${PG_PORT}
    depends_on:
      - db
  
  db:
    container_name: db-oxygen
    image: postgres:16
    ports:
      - ${PG_PORT}:${PG_PORT}
    environment:
      - POSTGRES_USER=${PG_USER} #doit matcher avec PG_USER
      - POSTGRES_PASSWORD=${PG_PASSWORD} #doit matcher avec PG_PASSWORD
      - POSTGRES_DB=${PG_DB} #doit matcher avec PG_DB
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: {}